### PR TITLE
Remove GRUS from reports

### PR DESCRIPTION
**Pull request by sofiahag**

### CODE REVIEW

**Review by aanil — COMMENTED** [review]
`ngi_reports.py` seems to have an option for Uppmax id. Is it something we want to keep?
`   parser.add_argument('-u', '--uppmax_id', default=None, action="store", help="Given UPPMAX id will be used while generating report")`

**Comment by sofiahag** [comment]
> `ngi_reports.py` seems to have an option for Uppmax id. Is it something we want to keep? ` parser.add_argument('-u', '--uppmax_id', default=None, action="store", help="Given UPPMAX id will be used while generating report")`

I think we can remove all instances of UPPMAX right? I see that UPPMAX is mentioned in multiple places. I'll remove them! 👍🏻

**Comment by aanil** [comment]
We don't need to remove it where its mentioned as computational infrastructure.

**Comment by sofiahag** [comment]
Ok:ed by Johannes and Pär! 👍🏻

**Review by aanil — APPROVED** [review]
👍

**Pull request merged**
