### PR TITLE
Config file fix for IRMA

### PR DESCRIPTION
**Pull request by senthil10**
Same like previous [PR](https://github.com/NationalGenomicsInfrastructure/ngi_reports/pull/76), `IRMA` cluster don't have a home directory, so would be better to point the config file via an `ENV` variable.

@ewels or @sylvinite should be an easy merge :)

### CODE REVIEW

**Comment by sylvinite** [comment]
Looks good, although there's a spelling error in the error message.

**Comment by senthil10** [comment]
image

**Comment by senthil10** [comment]
**TYPO FIXED** 🔊 🔊

**Comment by Galithil** [comment]
why are you a girl, senthil ?

**Comment by senthil10** [comment]
Is that a girl 😳  oh yeah it is 😅 
But not me, I am 👨  and I am just sick 😷

**Comment by Galithil** [comment]
You must be pretty sick then. Oh well. Get better.

**Pull request merged**
