### PR TITLE
Update Scilifelab logo in the template

### PR DESCRIPTION
**Pull request by aanil**
Removed python2 ascii workaround for special characters as well because all strings are unicode in py3. It was showing up as binary strings.

### CODE REVIEW

**Comment by aanil** [comment]
How it looks like
Screen Shot 2020-09-11 at 17 29 53

**Review by ssjunnebo — APPROVED** [review]
Looks good! 👍

**Review by ewels — APPROVED** [review]
LGTM!

**Review by alneberg — APPROVED** [review]
Looks good!

**Pull request merged**
