### PR TITLE
Adjustments for SWEDAC

### PR DESCRIPTION
**Pull request by senthil10**
In this **PR** made some layout adjustments for `SWEDAC` and some small fixes like sorting samples, etc

### CODE REVIEW

**Comment by ewels** [comment]
Nice! Looks good..

**Comment by senthil10** [comment]
@ewels : Tack for the help in moving `SWEDAC` logo up :)

**Comment by b97pla** [comment]
@senthil10 @ewels just checking: does this affect the NGI reports for us in Uppsala?

**Comment by senthil10** [comment]
@b97pla : Hej, It shouldn't affect I believe (as the main change was made and based upon `project_summary.md`). However, are you using those `template` (project_summary.md) or the changed `pandoc_filters` and `latex/html` template ? if not it should be fine.

**Comment by b97pla** [comment]
afaik we're only using the `ign_sample_report` template. tbh, I don't know if the `pandoc_filters`and `latex/html` stuff affects this.. maybe @ewels knows more

**Comment by ewels** [comment]
Nope, shouldn't affect you at all as it's essentially report specific (and you guys don't use this report). The new Swedac logo thing is only used if you add '[swedac]' to your report markdown.

**Comment by ewels** [comment]
@senthil10 - do you have an example report I could look at before I merge? Email / slack, not here.

**Comment by senthil10** [comment]
@ewels : Pushed the `commit` with logo text issues and **TACK** for helping with `html` fix :)

**Comment by ewels** [comment]
Nice! Bra jobbat!

**Comment by senthil10** [comment]
Tack Tack :)

**Pull request merged**
